name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Use Node.js
        with:
          node-version: '20.x'
      - run: npm ci # or yarn install
      - run: npm run lint